import { StyleSheet } from '@react-pdf/renderer';

export const C = {
  primary: '#0066CC',
  primaryDark: '#004d99',
  navy: '#0D2640',
  deep: '#0D2640',
  green: '#2E9E70',
  accent: '#CC6600',
  orange: '#CC6600',
  red: '#EF4444',
  surface: '#F6F6F6',
  white: '#FFFFFF',
  border: '#d1d5db',
  textPrimary: '#0D2640',
  textSecondary: '#4b5563',
  textTertiary: '#9CA3AF',
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xl2: 32,
  },
  fontSize: {
    xs: 10,
    sm: 11,
    md: 12,
    base: 13,
    lg: 14,
    xl: 16,
    xl2: 18,
    xl3: 20,
    xl4: 28,
    xl5: 32,
  },
};

export const styles = StyleSheet.create({
  page: {
    width: 1080,
    height: 1920,
    padding: 36,
    backgroundColor: C.surface,
    fontFamily: 'Inter',
    color: C.navy,
  },
  logoHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginBottom: 24,
  },
  logo: {
    width: 120,
    height: 40,
  },
  greeting: {
    fontSize: 32,
    fontWeight: 800,
    color: C.navy,
    marginBottom: 8,
    fontFamily: 'Inter Tight',
  },
  greetingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  planBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(0,0,0,0.05)',
    color: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 16,
  },
  subtitle: {
    fontSize: 18,
    color: '#6B7280',
    marginBottom: 16,
  },
  nextUpdate: {
    alignSelf: 'flex-start',
    backgroundColor: C.green,
    color: C.white,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: C.radius.full,
    fontSize: 14,
    fontWeight: 800,
    marginBottom: 40,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: C.navy,
    marginBottom: 12,
    letterSpacing: -0.02,
    fontFamily: 'Inter Tight',
  },
  sectionDivider: {
    height: 1,
    backgroundColor: C.border,
    marginBottom: 16,
    alignSelf: 'flex-start',
    width: 48,
  },
  card: {
    backgroundColor: C.white,
    borderRadius: C.radius.lg,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#9CA3AF',
    marginBottom: 12,
    fontFamily: 'Inter Tight',
  },
  navCard: {
    backgroundColor: C.navy,
    borderRadius: C.radius.xl,
    padding: 24,
    marginBottom: 24,
  },
  navCardTitle: {
    fontSize: 14,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: 'rgba(255,255,255,0.7)',
    marginBottom: 8,
    fontFamily: 'Inter Tight',
  },
  navCardValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 12,
    marginBottom: 4,
  },
  navCardAnterior: {
    fontSize: 18,
    color: 'rgba(255,255,255,0.6)',
    fontWeight: 700,
  },
  navCardActual: {
    fontSize: 28,
    fontWeight: 800,
    color: C.white,
    fontFamily: 'Inter Tight',
  },
  navCardUnit: {
    fontSize: 18,
    color: 'rgba(255,255,255,0.6)',
    fontWeight: 700,
  },
  navCardSubtext: {
    fontSize: 12,
    fontWeight: 700,
    color: 'rgba(255,255,255,0.5)',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginTop: 2,
  },
  navCardDelta: {
    backgroundColor: C.green,
    color: C.white,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 800,
  },
  measureGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  measureCard: {
    width: 468,
    backgroundColor: C.white,
    borderRadius: C.radius.lg,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  measureTitle: {
    fontSize: 12,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#9CA3AF',
    marginBottom: 8,
    fontFamily: 'Inter Tight',
  },
  statRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 12,
    marginBottom: 8,
  },
  statAnterior: {
    fontSize: 18,
    color: '#9CA3AF',
    fontWeight: 700,
  },
  statActual: {
    fontSize: 28,
    fontWeight: 800,
    color: C.navy,
    fontFamily: 'Inter Tight',
  },
  statDelta: {
    backgroundColor: C.green,
    color: C.white,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 800,
  },
  greenCard: {
    backgroundColor: C.green,
    borderRadius: C.radius.xl,
    padding: 24,
    marginBottom: 24,
  },
  greenCardTitle: {
    fontSize: 14,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: 'rgba(255,255,255,0.8)',
    marginBottom: 8,
    fontFamily: 'Inter Tight',
  },
  greenCardValue: {
    fontSize: 28,
    fontWeight: 800,
    color: C.white,
    fontFamily: 'Inter Tight',
  },
  progressBar: {
    height: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 6,
    marginTop: 12,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: C.white,
    borderRadius: 6,
  },
  miniGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  miniCard: {
    width: 228,
    backgroundColor: C.white,
    borderRadius: C.radius.lg,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  miniTitle: {
    fontSize: 12,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#9CA3AF',
    marginBottom: 8,
    fontFamily: 'Inter Tight',
  },
  miniValue: {
    fontSize: 22,
    fontWeight: 800,
    color: C.navy,
    fontFamily: 'Inter Tight',
  },
  miniProgress: {
    height: 8,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
    marginTop: 12,
    overflow: 'hidden',
  },
  miniProgressFill: {
    height: '100%',
    backgroundColor: '#0D2640',
    borderRadius: 4,
  },
  macroGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 16,
  },
  macroPill: {
    backgroundColor: C.navy,
    color: C.white,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    fontSize: 14,
    fontWeight: 800,
  },
  strategyPill: {
    backgroundColor: C.primary,
    color: C.white,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    fontSize: 14,
    fontWeight: 800,
  },
  exerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  exerciseCode: {
    width: 32,
    height: 32,
    borderRadius: C.radius.full,
    backgroundColor: C.navy,
    color: C.white,
    textAlign: 'center',
    lineHeight: 32,
    fontSize: 12,
    fontWeight: 800,
    marginRight: 12,
  },
  exerciseName: {
    flex: 1,
    fontSize: 14,
    fontWeight: 700,
    color: C.navy,
  },
  exerciseDetail: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 2,
  },
  exerciseBadgeTecnica: {
    fontSize: 11,
    fontWeight: 800,
    marginTop: 2,
  },
  clinicalItem: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 6,
  },
  clinicalNumber: {
    fontSize: 14,
    fontWeight: 700,
    color: C.primary,
  },
  clinicalText: {
    flex: 1,
    fontSize: 14,
    color: '#4B5563',
  },
  footer: {
    marginTop: 32,
    textAlign: 'center',
    fontSize: 12,
    color: '#9CA3AF',
  },
  pageFooter: {
    position: 'absolute',
    bottom: 36,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageFooterLogo: {
    width: 120,
    height: 40,
  },
  divider: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginVertical: 16,
  },
  link: {
    color: C.primary,
    textDecoration: 'none',
    fontSize: 12,
  },
  guideHeader: {
    backgroundColor: C.navy,
    borderRadius: C.radius.xl,
    padding: 24,
    marginBottom: 24,
  },
  guideHeaderTitle: {
    fontSize: 14,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: 'rgba(255,255,255,0.7)',
    marginBottom: 4,
    fontFamily: 'Inter Tight',
  },
  guideHeaderSubtitle: {
    fontSize: 28,
    fontWeight: 800,
    color: C.white,
    fontFamily: 'Inter Tight',
  },
  faqItem: {
    backgroundColor: C.white,
    borderRadius: C.radius.lg,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  faqQuestion: {
    fontSize: 14,
    fontWeight: 700,
    color: C.navy,
    marginBottom: 8,
    fontFamily: 'Inter Tight',
  },
  faqAnswer: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 1.5,
  },
  splitRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  splitCol: {
    flex: 1,
    backgroundColor: C.white,
    borderRadius: C.radius.lg,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  splitLabel: {
    fontSize: 14,
    fontWeight: 700,
    color: C.navy,
    marginBottom: 8,
    fontFamily: 'Inter Tight',
  },
  gridItem: {
    backgroundColor: C.white,
    borderRadius: C.radius.lg,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 16,
  },
  gridItemTitle: {
    fontSize: 12,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#9CA3AF',
    marginBottom: 8,
    fontFamily: 'Inter Tight',
  },
  gridPill: {
    backgroundColor: C.green,
    color: C.white,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 800,
    marginRight: 8,
    marginBottom: 8,
  },
  columnsRow: {
    flexDirection: 'row',
    gap: 16,
  },
  column: {
    flex: 1,
    backgroundColor: C.white,
    borderRadius: C.radius.lg,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  columnTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: C.navy,
    marginBottom: 8,
    fontFamily: 'Inter Tight',
  },
  columnBody: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 1.5,
  },
  glossaryCat: {
    backgroundColor: C.white,
    borderRadius: C.radius.lg,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 16,
  },
  glossaryCatTitle: {
    fontSize: 14,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: C.navy,
    marginBottom: 12,
    fontFamily: 'Inter Tight',
  },
  glossaryTerm: {
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  glossaryTermTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: C.navy,
    marginBottom: 4,
    fontFamily: 'Inter Tight',
  },
  glossaryTermDef: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 1.5,
  },
  dayLabel: {
    fontSize: 18,
    fontWeight: 800,
    color: C.navy,
    marginBottom: 16,
    fontFamily: 'Inter Tight',
  },
  restDay: {
    fontSize: 14,
    color: '#6B7280',
    fontStyle: 'italic',
  },
  warmupSection: {
    marginBottom: 24,
  },
  warmupTitle: {
    fontSize: 12,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#9CA3AF',
    marginBottom: 12,
    fontFamily: 'Inter Tight',
  },
  bloqueHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  bloqueTitle: {
    fontSize: 12,
    fontWeight: 800,
    color: '#9CA3AF',
    fontFamily: 'Inter Tight',
  },
  bloqueTypeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  bloqueTypeText: {
    fontSize: 11,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Inter Tight',
  },
  bloqueIndicacion: {
    fontSize: 11,
    color: '#6B7280',
    marginBottom: 8,
    marginTop: 2,
    lineHeight: 1.4,
  },
  multiExerciseContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  multiLine: {
    position: 'absolute',
    left: 3,
    top: 16,
    bottom: 0,
    width: 2,
    backgroundColor: '#E5E7EB',
  },
  exerciseOptionBadge: {
    width: 32,
    height: 32,
    borderRadius: C.radius.full,
    backgroundColor: C.primary,
    color: C.white,
    textAlign: 'center',
    lineHeight: 32,
    fontSize: 14,
    fontWeight: 800,
    marginRight: 12,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    paddingVertical: 10,
  },
  tableCell: {
    flex: 1,
    fontSize: 13,
    color: C.navy,
    paddingRight: 12,
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottomWidth: 2,
    borderBottomColor: C.navy,
    paddingBottom: 10,
    marginBottom: 10,
  },
  tableHeaderCell: {
    flex: 1,
    fontSize: C.fontSize.sm,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: C.textTertiary,
    paddingRight: C.spacing.sm,
    fontFamily: 'Inter Tight',
  },
  exerciseTableContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: C.radius.lg,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
    marginBottom: 16,
  },
  exerciseTableHeader: {
    height: 32,
    backgroundColor: C.surface,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    borderRadius: C.radius.lg,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  exerciseTableHeaderCell: {
    fontSize: 10,
    fontWeight: 700,
    color: C.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Inter Tight',
  },
  exerciseTableRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  exerciseTableRowLast: {
    borderBottomWidth: 0,
  },
  exerciseTableRowCell: {
    fontSize: 10,
    color: '#0D2640',
  },
  exerciseTableColTipo: { width: 70 },
  exerciseTableColSerie: { width: 42, alignItems: 'center', justifyContent: 'flex-start' },
  exerciseTableColVideo: { width: 36, alignItems: 'center', justifyContent: 'center' },
  exerciseTableColEjercicio: { flex: 1, minWidth: 180 },
  exerciseTableColSets: { width: 42, textAlign: 'center', alignItems: 'center' },
  exerciseTableColReps: { width: 50, textAlign: 'center', alignItems: 'center' },
  exerciseTableColTecnica: { width: 64, textAlign: 'center', alignItems: 'center' },
  exerciseTableColRir: { width: 30, textAlign: 'center', alignItems: 'center' },
  exerciseTableColDescanso: { width: 54, textAlign: 'center', alignItems: 'center' },
  exerciseTableColNotas: { flex: 1, minWidth: 120 },
  blockBadge: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    marginBottom: 8,
  },
  blockBadgeText: {
    fontSize: 8,
    fontWeight: 800,
    color: '#0D2640',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Inter Tight',
  },
  groupSubHeader: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  groupSubHeaderText: {
    fontSize: 8,
    fontWeight: 700,
    color: '#6B7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Inter Tight',
  },
  coverPage: {
    backgroundColor: C.primary,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 48,
  },
  coverContent: {
    alignItems: 'center',
    gap: 32,
  },
  coverLogo: {
    width: 360,
    height: 160,
    resizeMode: 'contain',
  },
  coverTitle: {
    fontSize: 40,
    fontWeight: 800,
    color: C.white,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 2,
    fontFamily: 'Inter Tight',
  },
  coverTagline: {
    fontSize: 18,
    fontWeight: 500,
    color: 'rgba(255,255,255,0.9)',
    textAlign: 'center',
    fontStyle: 'italic',
    paddingHorizontal: 80,
    lineHeight: 1.6,
  },
  coverFooter: {
    position: 'absolute',
    bottom: 48,
    left: 0,
    right: 0,
    alignItems: 'center',
    gap: 4,
  },
  coverFooterText: {
    fontSize: 14,
    fontWeight: 600,
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'center',
  },
  nutritionTableContainer: {
    backgroundColor: C.white,
    borderRadius: C.radius.lg,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  nutritionDayHeader: {
    backgroundColor: C.navy,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    marginBottom: 12,
    marginTop: 16,
  },
  nutritionDayTitle: {
    color: C.white,
    fontSize: 14,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontFamily: 'Inter Tight',
  },
  mealRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  mealTimeCell: {
    width: 80,
    fontSize: 12,
    fontWeight: 800,
    color: C.green,
    fontFamily: 'Inter Tight',
  },
  mealNameCell: {
    width: 120,
    fontSize: 13,
    fontWeight: 700,
    color: C.navy,
    fontFamily: 'Inter Tight',
  },
  mealMacrosCell: {
    width: 140,
    fontSize: 12,
    color: '#6B7280',
  },
  mealFoodsCell: {
    flex: 1,
    fontSize: 12,
    color: '#4B5563',
  },
  nutritionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 16,
    marginBottom: 16,
  },
  nutritionCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  nutritionTimePill: {
    backgroundColor: C.green,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    marginRight: 12,
  },
  nutritionTimeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: 800,
    textTransform: 'uppercase',
  },
  nutritionMealName: {
    fontSize: 12,
    fontWeight: 700,
    color: C.navy,
    flex: 1,
    fontFamily: 'Inter Tight',
  },
  nutritionKcal: {
    fontSize: 10,
    fontWeight: 700,
    color: C.navy,
  },
  nutritionMacros: {
    fontSize: 9,
    color: '#6B7280',
  },
  nutritionMenuPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    marginLeft: 12,
  },
  nutritionMenuText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: 800,
    textTransform: 'uppercase',
  },
  nutritionFoodHeader: {
    flexDirection: 'row',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    marginBottom: 4,
  },
  nutritionFoodRow: {
    flexDirection: 'row',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  nutritionFoodRowLast: {
    borderBottomWidth: 0,
  },
  nutritionFoodName: {
    flex: 1,
    fontSize: 9,
    color: '#374151',
  },
  nutritionFoodKcal: {
    width: 90,
    textAlign: 'right',
    fontSize: 9,
    color: '#6B7280',
  },
  nutritionFoodMacros: {
    width: 110,
    textAlign: 'center',
    fontSize: 9,
    color: '#6B7280',
  },
  categoryHeader: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  categoryHeaderText: {
    fontSize: 8,
    fontWeight: 700,
    color: '#6B7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Inter Tight',
  },
});
